
```{r}
library(tidyverse)
library(dslabs)
library(dplyr)
library(caret)
library(ggplot2)

data(heights)

# define the outcome and predictors
y <- heights$sex
x <- heights$height

# generate training and test sets
set.seed(2,sample.kind = "Rounding") 
test_index <- createDataPartition(y,times =1, p = 0.5, list = FALSE)
test_set <- heights[test_index, ]
train_set <- heights[-test_index, ]

#guess the outcome
y_hat <- sample(c("Male","Female"),length(test_index),replace = TRUE)
y_hat <- sample(c("Male", "Female"), length(test_index), replace = TRUE) %>% 
  factor(levels = levels(test_set$sex))

#compute accuracy
mean(y_hat == test_set$sex)
heights %>% group_by(sex) %>% summarize(mean(height),sd(height))
y_hat <- ifelse(x > 62, "Male", "Female") %>% factor(levels = levels(test_set$sex))
mean(y == y_hat)

# examine the accuracy of 10 cutoffs
cutoff <- seq(61,70)
accuracy <- map_dbl(cutoff, function(x){
  y_hat <- ifelse(train_set$height > x, "Male", "Female") %>%
    factor(levels = levels(test_set$sex))
    mean(train_set$sex == y_hat)
})

data.frame(cutoff,accuracy) %>%
  ggplot(aes(cutoff,accuracy)) + geom_point() + geom_line ()
max(accuracy)

best_cutoff <- cutoff[which.max(accuracy)]

y_hat <- ifelse(test_set$height > best_cutoff, "Male", "Female") %>%
  factor(levels = levels(test_set$sex))
mean(y_hat == test_set$sex)
```
```{r}
table(predicted = y_hat, actual = test_set$sex)
test_set %>% mutate(y_hat = y_hat) %>%
  group_by(sex) %>% 
  summarize(accuracy = mean(y_hat == sex))
prev <- mean(y == "Male")  

confusionMatrix(data = y_hat, reference = test_set$sex)
```
```{r}
# maximize F-core
cutoff <- seq(61,70)
F_1 <- map_dbl(cutoff, function(x){
  y_hat <- ifelse(train_set$height > x, "Male", "Female") %>%
    factor(levels = levels(test_set$sex))
  F_meas(data = y_hat, reference = factor(train_set$sex))
})

data.frame(cutoff,F_1) %>%
  ggplot(aes(cutoff,F_1)) + geom_point() + geom_line()
max(F_1)
best_cutoff <- cutoff[which.max(F_1)]

y_hat <- ifelse(test_set$height > best_cutoff,"Male","Female") %>%
  factor(levels = levels(test_set$sex))

F_meas(data = y_hat, reference = factor(test_set$sex))
sensitivity(data = y_hat, reference = test_set$sex)
specificity(data = y_hat, reference = test_set$sex)
confusionMatrix(data = y_hat, reference = test_set$sex)
```
```{r}
p <- 0.9
n <- length(test_index)
y_hat <- sample(c("Male","Female"), n,replace = TRUE, prob=c(p,1-p)) %>%
  factor(levels = levels(test_set$sex))
mean(y_hat == test_set$sex)
  
#ROC curve
probs <- seq(0,1,length.out = 10)
guessing <- map_df(probs,function(p){
  y_hat <- sample(c("Male","Female"), n,replace = TRUE, prob=c(p,1-p)) %>%
    factor(levels = levels(test_set$sex))
  list(method = "Guessing",
       FPR = 1- specificity(y_hat,test_set$sex),
       TPR = sensitivity(y_hat,test_set$sex))
})
guessing %>% qplot(FPR,TPR, data =., xlab = "1- Specificity", ylab = "Sensitivity")

cutoffs <- c(50,seq(60,75),80)
height_cutoff <- map_df(cutoffs, function(x){
  y_hat <- ifelse(test_set$height > x, "Male", "Female") %>%
    factor(levels = levels(test_set$sex))
  list(method ="Cutoff",
       FPR = 1- specificity(y_hat,test_set$sex),
       TPR = sensitivity(y_hat,test_set$sex))
})

#plot both curve together
bind_rows(guessing, height_cutoff) %>%
  ggplot(aes(FPR,TPR,color = method)) +
  geom_line() +
  geom_point() +
  xlab("1 - Specificity") +
  ylab("Sensitivity")

library(ggrepel)
map_df(cutoffs, function(x){
  y_hat <- ifelse(test_set$height > x, "Male", "Female") %>%
    factor(levels = levels(test_set$sex))
  list(method ="Cutoff",
       cutoff = x,
       FPR = 1- specificity(y_hat,test_set$sex),
       TPR = sensitivity(y_hat,test_set$sex))
}) %>%
  ggplot(aes(FPR,TPR,label = cutoff)) +
  geom_line() + geom_point() +
  geom_text_repel(nudge_x = 0.01, nudge_y = 0.01)

# plot precision against recall
guessing <- map_df(probs,function(p){
  y_hat <- sample(c("Male","Female"), n,replace = TRUE, prob=c(p,1-p)) %>%
    factor(levels = levels(test_set$sex))
  list(method = "Guessing",
       recall = sensitivity(y_hat,test_set$sex),
       precision = precision(y_hat,test_set$sex))
})
height_cutoff <- map_df(cutoffs, function(x){
  y_hat <- ifelse(test_set$height > x, "Male", "Female") %>%
    factor(levels = levels(test_set$sex))
  list(method ="Cutoff",
       recall = sensitivity(y_hat,test_set$sex),
       precision = precision(y_hat,test_set$sex))
})

bind_rows(guessing, height_cutoff) %>%
  ggplot(aes(recall,precision,color = method)) +
  geom_line() +
  geom_point() 

```
```{r}
library(dslabs)
library(dplyr)
library(lubridate)
data(reported_heights)

dat <- mutate(reported_heights, date_time = ymd_hms(time_stamp)) %>%
  filter(date_time >= make_date(2016, 01, 25) & date_time < make_date(2016, 02, 1)) %>%
  mutate(type = ifelse(day(date_time) == 25 & hour(date_time) == 8 & between(minute(date_time), 15, 30), "inclass","online")) %>%
  select(sex, type)

y <- factor(dat$sex, c("Female", "Male"))
x <- dat$type

prop.table(table(dat))
dat %>% group_by(type) %>% summarize(prop_female = mean(sex == "Female"))

y_hat <- ifelse(x == "online", "Male", "Female") %>% factor(levels = levels(y))
mean(y_hat == y)

confusionMatrix(data = y_hat, reference = y)
table(y_hat,y)
sensitivity(y_hat,y)
```
```{r}
library(caret)
data(iris)
iris <- iris[-which(iris$Species == 'setosa'),]
y <- iris$Species

set.seed(2, sample.kind="Rounding") # if using R 3.6 or later
test_index <- createDataPartition(y,times =1, p=0.5, list = FALSE)
test <- iris[test_index,]
train <- iris[-test_index,]

var <- train$Petal.Length
cutoff <- seq(min(var),max(var), by =0.1)
accuracy <- map_dbl(cutoff, function(x){
  y_hat <- ifelse(var > x, "virginica", "versicolor") %>%
    factor(levels = levels(train$Species))
    mean(train$Species == y_hat)
})
max(accuracy)


foo <- function(x){
	rangedValues <- seq(range(x)[1],range(x)[2],by=0.1)
	sapply(rangedValues,function(i){
		y_hat <- ifelse(x>i,'virginica','versicolor')
		mean(y_hat==train$Species)
	})
}
predictions <- apply(train[,-5],2,foo)
sapply(predictions,max)	

x <- train$Petal.Length
rangedValues <- seq(range(x)[1],range(x)[2],by=0.1)
best1 <- rangedValues[which.max(predictions[[3]])]

x <- train$Petal.Width
rangedValues <- seq(range(x)[1],range(x)[2],by=0.1)
best2 <- rangedValues[which.max(predictions[[4]])]


y_hat <- ifelse(test$Petal.Length> best1,'virginica','versicolor')
mean(y_hat==test$Species)

y_hat <- ifelse(test$Petal.Width > best2,'virginica','versicolor')
mean(y_hat==test$Species)

y_hat <- ifelse(test$Petal.Length> best1 | test$Petal.Width > best2,'virginica','versicolor')
mean(y_hat==test$Species)


predictions <- apply(test[,-5],2,foo)
sapply(predictions,max)

plot(iris,pch=21,bg=iris$Species)
```
```{r}
# set.seed(1) # if using R 3.5 or earlier
set.seed(1, sample.kind = "Rounding") # if using R 3.6 or later
disease <- sample(c(0,1), size=1e6, replace=TRUE, prob=c(0.98,0.02))
test <- rep(NA, 1e6)
test[disease==0] <- sample(c(0,1), size=sum(disease==0), replace=TRUE, prob=c(0.90,0.10))
test[disease==1] <- sample(c(0,1), size=sum(disease==1), replace=TRUE, prob=c(0.15, 0.85))
mean(test)

mean(disease[test ==0])
mean(disease[test ==1])
mean(disease[test ==1])/mean(disease)
```
```{r}

library(dslabs)
library(tidyverse)
data("heights")
heights %>% mutate(height = round(height)) %>%
  group_by(height) %>%
  summarize(p = mean(sex == "Male")) %>%
	qplot(height, p, data =.)

heights %>% mutate(g = cut(height,quantile(height,seq(0,1,0.1)),include.lowest = TRUE)) %>%
  group_by(g) %>%
  summarize(p = mean(sex == "Male"),height = mean(height)) %>%
	qplot(height, p, data =.)

head(heights)
```
```{r}
Sigma <- 9*matrix(c(1,0.5,0.5,1), 2, 2)
dat <- MASS::mvrnorm(n=10000,c(69,69),Sigma) %>%
  data.frame() %>% setNames(c("x","y"))

plot(dat)
ps <- seq(0,1,0.1)
dat %>% mutate(g = cut(x,quantile(x,ps),include.Lowest =TRUE)) %>%
  group_by(g) %>% summarize(y= mean(y), x=mean(x)) %>%
  qplot(x,y,data =.)
```

