
```{r}
library(tidyverse)
library(caret)

```
```{r}
set.seed(1996, sample.kind = "Rounding")
n <- 1000
p<- 10000
x <- matrix(rnorm(n*p),n,p)
colnames(x) <- paste("x",1:ncol(x),sep ="_")
y <- rbinom(n,1,0.5) %>% factor()

x_subset <- x[,sample(p,100)]
```
```{r}
fit <- train(x_subset, y, method = "glm")
fit$results
```
```{r}
install.packages("BiocManager")
BiocManager::install("genefilter")
library(genefilter)
tt <- colttests(x, y)

pvals <- tt$p.value

ind <- which(pvals <= 0.01)
length(ind)

x_subset <- x[,ind]
dim(x_subset)

fit <- train(x_subset, y, method = "glm")
fit$results
```
```{r}
          
fit <- train(x_subset, y, method = "knn", tuneGrid = data.frame(k = seq(101, 301, 25)))
ggplot(fit)
```
```{r}
library(dslabs)
library(caret)
data("tissue_gene_expression")
dat <- tissue_gene_expression 

fit <- train(dat$x, dat$y, method = "knn", tuneGrid = data.frame(k = seq(1,7,2)))
ggplot(fit)


data("tissue_gene_expression")
fit <- with(tissue_gene_expression, train(x, y, method = "knn", tuneGrid = data.frame( k = seq(1, 7, 2))))
ggplot(fit)
fit$results
```
```{r}
n <- 10^6
income <- 10^(rnorm(n,log10(45000),log10(3)))
qplot(log10(income), bins = 30, color=(I("black")))

m <- median(income)
m

set.seed(1, sample.kind = "Rounding")
library(gridExtra)
N <- 250
B <- 10^5
M <- replicate(B, {
  X <- sample(income,N)
  median(X)
})
p1 <- qplot(M, bins =30, color = I("black"))
p2 <- qplot(sample = scale(M)) + geom_abline()
grid.arrange(p1,p2,ncol =2)

mean(M); sd(M)

```
```{r}
B <- 10^5
M_star <- replicate(B, {
  X <- sample(income,N, replace = TRUE)
  median(X)
})

tibble(monte_carlo = sort(M), bootstrap =sort(M_star)) %>%
  qplot(monte_carlo, bootstrap, data =.) +
  geom_abline()

quantile(M,c(0.05,0.95))
quantile(M_star,c(0.05,0.95))

mean(M) + 1.96 * sd(M) * c(-1,1)

mean(M_star) + 1.96 * sd(M_star) * c(-1, 1)
```
```{r}
library(dslabs)
library(caret)
data(mnist_27)
# set.seed(1995) # if R 3.5 or earlier
set.seed(1995, sample.kind="Rounding") # if R 3.6 or later
indexes <- createResample(mnist_27$train$y, 10)

length(which(indexes[[1]] ==3))
length(which(indexes[[1]] ==4))
length(which(indexes[[1]] ==7))

 n <- c(1:10) 
x <- sapply(n, function(n){
   sum(indexes[[n]] == 3)
   })
sum(x) 

x <-sapply(indexes, function(ind){
	sum(ind == 3)
})
sum(x)

```
```{r}
set.seed(1, sample.kind="Rounding") # if R 3.6 or later
B <- 10000
q75 <- replicate(B, {
  y <- rnorm(100,0,1)
  quantile(y,0.75)
})

mean(q75)
sd(q75)

set.seed(1, sample.kind="Rounding") # if R 3.6 or later
y <- rnorm(100,0,1)
quantile(y,0.75)
set.seed(1, sample.kind="Rounding") # if R 3.6 or later
ind <- createResample(y, 10000)
q_75 = sapply(ind, function(ind){
	y_star <- y[ind]
	quantile(y_star, 0.75)
  })

mean(q_75)
sd(q_75)

```
```{r}
library("caret")
data("heights")

y <-heights$height
set.seed(2, sample.kind="Rounding") # if R 3.6 or later
test_index <- createDataPartition(y,times =1, p = 0.5, list =FALSE)
train_set <- heights %>% slice(-test_index)
test_set <- heights %>% slice(test_index)

# Estimating averages and standard deviations
params <- train_set %>%
  group_by(sex) %>%
  summarize(avg = mean(height), sd = sd(height))
params

# Estimating averages and standard deviations
pi <- train_set %>% summarize(pi = mean(sex =="Female")) %>% pull(pi)

# Getting an actual rule
x <- test_set$height
f0 <- dnorm(x, params$avg[2], params$sd[2])
f1 <- dnorm(x, params$avg[1], params$sd[1])
p_hat_bayes <- f1*pi / (f1*pi + f0*(1-pi))
 qplot(x,p_hat_bayes)
```

