

```{r}
library(dslabs)
library(tidyverse)
data("movielens")

train_small <- movielens %>%
  group_by(movieId) %>%
  filter(n() >50 | movieId == 3252) %>% ungroup()%>%
  group_by(userId) %>% 
  filter(n() >= 50) %>% ungroup()


y <- train_small %>%
  select(userId, movieId,rating) %>%
  spread(movieId, rating) %>%
  as.matrix()

rownames(y) <- y[,1]
y <- y[,-1]

movie_titles <- movielens %>%
  select(movieId, title) %>%
  distinct()

colnames(y) <- with(movie_titles, title[match(colnames(y),movieId)])

y <-sweep(y,1,rowMeans(y,na.rm =TRUE))
y <-sweep(y,2,colMeans(y,na.rm =TRUE))
```
```{r}
m_1 <- "Godfather, The"
m_2 <- "Godfather: Part II, The"
qplot(y[ ,m_1], y[,m_2], xlab = m_1, ylab = m_2)

m_1 <- "Godfather, The"
m_3 <- "Goodfellas"
qplot(y[ ,m_1], y[,m_3], xlab = m_1, ylab = m_3)

m_4 <- "You've Got Mail" 
m_5 <- "Sleepless in Seattle" 
qplot(y[ ,m_4], y[,m_5], xlab = m_4, ylab = m_5)

cor(y[, c(m_1, m_2, m_3, m_4, m_5)], use="pairwise.complete") %>% 
     knitr::kable()
```
```{r}
set.seed(1,sample.kind = "Rounding")
options(digits = 2)
m_6 <- "Scent of a Woman"
Q <- matrix(c(1 , 1, 1, -1, -1), ncol=1)
rownames(Q) <- c(m_1, m_2, m_3, m_4, m_5)
P <- matrix(rep(c(2,0,-2), c(3,5,4)), ncol=1)
rownames(P) <- 1:nrow(P)

X <- jitter(P%*%t(Q))
X %>% knitr::kable(align = "c")

cor(X)

t(Q) %>% knitr::kable(aling="c")

```
```{r}
set.seed(1,sample.kind = "Rounding")
options(digits = 2)
m_6 <- "Scent of a Woman"

Q <- cbind(c(1 , 1, 1, -1, -1, -1), 
           c(1 , 1, -1, -1, -1, 1))
rownames(Q) <- c(m_1, m_2, m_3, m_4, m_5, m_6)
P <- cbind(rep(c(2,0,-2), c(3,5,4)), 
           c(-1,1,1,0,0,1,1,1,0,-1,-1,-1))/2
rownames(P) <- 1:nrow(X)

X <- jitter(P%*%t(Q), factor=1)
X %>% knitr::kable(align = "c")

cor(X)  %>% knitr::kable(align = "c")
t(Q) %>% knitr::kable(align="c")


six_movies <- c(m_1, m_2, m_3, m_4, m_5, m_6)
tmp <- y[,six_movies]
cor(tmp, use="pairwise.complete")  %>% knitr::kable(align = "c")
```
```{r}
y[is.na(y)] <- 0
y <- sweep(y,1,rowMeans(y))
pca <- prcomp(y)

dim(pca$x)
dim(pca$rotation)
plot(pca$sdev)

var_explained <- cumsum(pca$sdev^2/sum(pca$sdev^2))
plot(var_explained)
```
```{r}
library(ggrepel)
pcs <- data.frame(pca$rotation, name = colnames(y))

pcs %>%  ggplot(aes(PC1, PC2)) + geom_point() + 
     geom_text_repel(aes(PC1, PC2, label=name),
                     data = filter(pcs, 
                                   PC1 < -0.1 | PC1 > 0.1 | PC2 < -0.075 | PC2 > 0.1))

pcs %>% select(name, PC1) %>% arrange(PC1) %>% slice(1:10)

pcs %>% select(name, PC1) %>% arrange(desc(PC1)) %>% slice(1:10)

pcs %>% select(name, PC2) %>% arrange(PC2) %>% slice(1:10)

pcs %>% select(name, PC2) %>% arrange(desc(PC2)) %>% slice(1:10)
```
```{r}
set.seed(1987, sample.kind="Rounding")
n <- 100
k <- 8
Sigma <- 64  * matrix(c(1, .75, .5, .75, 1, .5, .5, .5, 1), 3, 3) 
m <- MASS::mvrnorm(n, rep(0, 3), Sigma)
m <- m[order(rowMeans(m), decreasing = TRUE),]
y <- m %x% matrix(rep(1, k), nrow = 1) + matrix(rnorm(matrix(n*k*3)), n, k*3)
colnames(y) <- c(paste(rep("Math",k), 1:k, sep="_"),
                 paste(rep("Science",k), 1:k, sep="_"),
                 paste(rep("Arts",k), 1:k, sep="_"))


my_image <- function(x, zlim = range(x), ...){
	colors = rev(RColorBrewer::brewer.pal(9, "RdBu"))
	cols <- 1:ncol(x)
	rows <- 1:nrow(x)
	image(cols, rows, t(x[rev(rows),,drop=FALSE]), xaxt = "n", yaxt = "n",
			xlab="", ylab="",  col = colors, zlim = zlim, ...)
	abline(h=rows + 0.5, v = cols + 0.5)
	axis(side = 1, cols, colnames(x), las = 2)
}

my_image(y)
```
```{r}
my_image(cor(y), zlim = c(-1,1))
range(cor(y))
axis(side = 2, 1:ncol(y), rev(colnames(y)), las = 2)
```
```{r}
s <- svd(y)
names(s)

y_svd <- s$u %*% diag(s$d) %*% t(s$v)
max(abs(y-y_svd))



# or use Matrix:: colSums(y ** 2)
ss_y <- apply(y^2, 2, sum)
ss_yv <- apply((y%*%s$v)^2, 2, sum)
sum(ss_y)
sum(ss_yv)
sum(ss_y) - sum(ss_yv)

qplot(1:length(ss_y),ss_y)
qplot(1:length(ss_yv),ss_yv)

plot(ss_y)
plot(ss_yv)

qplot(ss_yv^0.5,s$d)

data.frame(x = sqrt(ss_yv), y = s$d) %>%
ggplot(aes(x,y)) +
geom_point()

sum(ss_yv[1:3])/sum(ss_yv)
sum(s$d[1:3]^2) / sum(s$d^2)

 identical(s$u %*% diag(s$d), sweep(s$u, 2, s$d, FUN = "*"))
  identical(s$u %*% t(diag(s$d)), sweep(s$u, 2, s$d, FUN = "*"))
```
```{r}
qplot(rowMeans(y),s$u[,1]*s$d[1])
plot(s$u[,1]*s$d[1], rowMeans(y))

my_image(s$v)
```
```{r}
plot(s$u[,1], ylim = c(-0.25,0.25))
plot(s$v[,1], ylim = c(-0.25,0.25))
with(s, my_image((u[, 1, drop=FALSE]*d[1]) %*% t(v[, 1, drop=FALSE])))
```
```{r}
resid <- y - with(s,(u[, 1, drop=FALSE]*d[1]) %*% t(v[, 1, drop=FALSE]))
my_image(cor(resid), zlim = c(-1,1))
axis(side = 2, 1:ncol(y), rev(colnames(y)), las = 2)
```
```{r}
plot(s$u[,2], ylim = c(-0.5,0.5))
plot(s$v[,2], ylim = c(-0.5,0.5))
with(s, my_image((u[, 2, drop=FALSE]*d[2]) %*% t(v[, 2, drop=FALSE])))
```
```{r}
resid <- y - with(s,sweep(u[, 1:2], 2, d[1:2], FUN="*") %*% t(v[, 1:2]))
my_image(cor(resid), zlim = c(-1,1))
axis(side = 2, 1:ncol(y), rev(colnames(y)), las = 2)
```
```{r}
plot(s$v[,3])

resid <- y - with(s,sweep(u[, 1:3], 2, d[1:3], FUN="*") %*% t(v[, 1:3]))
my_image(cor(resid), zlim = c(-1,1))
axis(side = 2, 1:ncol(y), rev(colnames(y)), las = 2)
```
```{r}
y_hat <- with(s,sweep(u[, 1:3], 2, d[1:3], FUN="*") %*% t(v[, 1:3]))
my_image(y, zlim = range(y))
my_image(y_hat, zlim = range(y))
my_image(y - y_hat, zlim = range(y))
```
```{r}
data("tissue_gene_expression")
dim(tissue_gene_expression$x)

pca <- prcomp(tissue_gene_expression$x)
data.frame(PC1 = pca$x[,1], PC2 = pca$x[,2],
           label=factor(tissue_gene_expression$y)) %>%
  ggplot(aes(PC1, PC2, fill=label))+
  geom_point(cex=3, pch=21)
```
```{r}
avg <- rowMeans(tissue_gene_expression$x)
data.frame(PC1 = pca$x[,1], avg = avg,
           label=factor(tissue_gene_expression$y)) %>%
  ggplot(aes(PC1, avg, fill=label))+
  geom_point(cex=3, pch=21)

cor(pca$x[,1], avg)
```
```{r}
 x <- with(tissue_gene_expression, sweep(x, 1, rowMeans(x)))
pc <- prcomp(x)
data.frame(pc_1 = pc$x[,1], pc_2 = pc$x[,2], 
	   tissue = tissue_gene_expression$y) %>%
	   ggplot(aes(pc_1, pc_2, color = tissue)) +
	   geom_point()
```
```{r}
data.frame( tissue = tissue_gene_expression$y,pc_7 = pc$x[,7]) %>%
ggplot(aes(tissue, pc_7)) + geom_boxplot() +
   scale_y_sqrt() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

for(i in 1:10){
	boxplot(pc$x[,i] ~ tissue_gene_expression$y, main = paste("PC", i))
}

data.frame( tissue = tissue_gene_expression$y,pc_7 = pc$x[,7]) %>%
  group_by(tissue) %>% summarize(avg = mean(pc_7)) %>% arrange(avg)
```
```{r}
qplot(1:nrow(x),pc$sdev)
summary(pc)
plot(summary(pc)$importance[3,])
```


