
```{r}
library(tidyverse)
library(dslabs)
if(!exists("mnist")) mnist <- read_mnist()

```
```{r}
class(mnist$train$images)

x <- mnist$train$images[1:1000,]
y <- mnist$train$labels[1:1000]
```
```{r}
my_vector <- 1:15
#fill the matrix by column
mat <- matrix(my_vector, 5,3)
mat
#fill by row
mat_t <- matrix(my_vector, 3,5, byrow = TRUE)
mat_t

# tranpose
identical(t(mat),mat_t)

grid <- matrix(x[3,], 28, 28)
image(1:28,1:28,grid)

image(1:28,1:28,grid[,28:1])
```
```{r}
sums <- rowSums(x)
avg <- rowMeans(x)

tibble(labels = as.factor(y), row_averages = avg) %>%
  qplot(labels, row_averages, data = ., geom = "boxplot")

avgs <- apply(x,1,mean) # 1 for rows, 2 for columns
sdss <- apply(x, 2, sd)
```
```{r}
library(matrixStats)
sds <- colSds(x)
qplot(sds, bins = "30", color = I("black"))
image(1:28,1:28,matrix(sds,28,28)[,28:1])

#extract columns and rows
x[,c(351,352)]
x[c(2,3),]
new_x <- x[,colSds(x) > 60]
dim(new_x)
class(x[,1])
dim(x[1,])

#preserve the matrix class
class(x[,1, drop = FALSE])
dim(x[,1, drop = FALSE])
```
```{r}
mat <- matrix(1:15,5,3)
mat[mat > 6 & mat <12] <- 0
mat

bin_x <- x
bin_x[bin_x < 255/2] <- 0
bin_x[bin_x > 255/2] <- 1

bin_X <- (x > 255/2)*1
```
```{r}
as.vector(mat)
qplot(as.vector(x), bin = 30, color = I("black"))
new_x <- x
new_x[new_x < 50] <- 0
```

```{r}
grid <- matrix(x[8,], 28, 28)
image(1:28,1:28,grid[,28:1])

grid <- matrix(bin_X[8,], 28, 28)
image(1:28,1:28,grid[,28:1])
```
```{r}
# scale each row of a matrix
(x - rowMeans(x))/ rowSds(x)

#scale each column
t(t(x) - colMeans(x))

#take each entry of a vector and subtracts it from the corresponding row or column
x_mean_0 <- sweep(x, 2, colMeans(x))
x_standardized <- sweep(x_mean_0, 2, colSds(x), FUN = "/")

qr(x)
```
```{r}
x <- matrix(rnorm(20*10), 20,10)
dim(x)
nrow(x)
ncol(x)

y <- sapply(x,mean)

```
```{r}
mnist <- read_mnist()
y <- rowMeans(mnist$train$images > 50 & mnist$train$images < 205)
qplot(as.factor(mnist$train$label), y, geom = "boxplot")
mean((mnist$train$images > 50 & mnist$train$images < 205)*1)
```


