
```{r}
library(tidyverse)
library(dslabs)
if(!exists("mnist")) mnist <- read_mnist()

```
```{r}
set.seed(0, sample.kind = "Rounding")
ind <- which(mnist$train$labels %in% c(2,7)) %>% sample(500)
#the predictors are in x and the labels in y
x <- mnist$train$images[ind,]
y <- mnist$train$labels[ind]

y[1:3]

x_1 <- x[1,]
x_2 <- x[2,]
x_3 <- x[3,]

# distance between two numbers
sqrt(sum((x_1-x_2)^2))
sqrt(sum((x_1 - x_3)^2))
sqrt(sum((x_2 - x_3)^2))

# compute distance using matrix algebra
sqrt(crossprod(x_1 - x_2))
sqrt(crossprod(x_1 - x_3))
sqrt(crossprod(x_2 - x_3))

# compute distance between each row
d <- dist(x)
class(d)
as.matrix(d)[1:3,1:3]

#visualize the distances
image(1:500,1:500,as.matrix(d))

# order the distance by labels
image(as.matrix(d)[order(y), order(y)])

#compute distance between predictors
d <-dist(t(x))
dim(as.matrix(d))

d_492 <- as.matrix(d)[492,]
image(1:28,1:28,matrix(d_492,28,28))
```
```{r}
library(dslabs)
data("tissue_gene_expression")
dim(tissue_gene_expression$x)
table(tissue_gene_expression$y)

d <-dist(tissue_gene_expression$x)
dim(as.matrix(d))

as.matrix(d)[c(1,2,39,40,73,74),c(1,2,39,40,73,74)]
image(as.matrix(d))
```
```{r}
library(tidyverse)
library(dslabs)

data(mnist_27)
mnist_27$test %>% ggplot(aes(x_1,x_2, color =y)) + geom_point()

#logistic regression
library(caret)
fit_glm <- glm(y ~ x_1 + x_2, data = mnist_27$train, family = "binomial")
p_hat_logistic <- predict(fit_glm, mnist_27$test, type = "response")
y_hat_logistic <- factor(ifelse(p_hat_logistic > 0.5, 7,2))
confusionMatrix(data = y_hat_logistic, reference = mnist_27$test$y)$overall[1]

# fir knn model
knn_fit <-knn3(y ~ ., data = mnist_27$train)

x <- as.matrix(mnist_27$train[,2:3] )
y <- mnist_27$train$y

knn_fit <- knn3(x,y)

knn_fit <-knn3(y ~ ., data = mnist_27$train, k =3)
y_hat_knn <- predict(knn_fit, mnist_27$test, type = "class")
confusionMatrix(data = y_hat_knn, reference = mnist_27$test$y)$overall[1]
```
```{r}
k<-401
knn_fit <-knn3(y ~ ., data = mnist_27$train, k =k)
y_hat_knn <- predict(knn_fit, mnist_27$train, type = "class")
confusionMatrix(data = y_hat_knn, reference = mnist_27$train$y)$overall[1]
y_hat_knn <- predict(knn_fit, mnist_27$test, type = "class")
confusionMatrix(data = y_hat_knn, reference = mnist_27$test$y)$overall[1]

#pick a k in knn
ks <- seq(3,251,2)
library(purrr)

accuracy <- map_df(ks, function(k){
  fit <-knn3(y ~ ., data = mnist_27$train, k =k)
  y_hat <- predict(fit, mnist_27$train, type = "class")
  train_error <- confusionMatrix(data = y_hat, reference = mnist_27$train$y)$overall["Accuracy"]
  y_hat <- predict(fit, mnist_27$test, type = "class")
  test_error <- confusionMatrix(data = y_hat, reference = mnist_27$test$y)$overall[1]
  tibble(k = k, train = train_error, test = test_error)
 })

# pick k that maximizes test_error
ks[which.max(accuracy$test)]
max(accuracy$test)
accuracy %>% ggplot() + 
  geom_line(aes(k,train, color = "train"), size = 1.5)  +
  geom_line(aes(k,test, color = "test"), size = 1.5) +
  scale_color_manual(name = "Colors", 
                     values = c("train" = "blue", "test" = "red"))
```
```{r}
library(dslabs)
library(caret)
data(heights)

set.seed(1, sample.kind = "Rounding")
test_index <- createDataPartition(heights$sex,times =1, p = 0.5, list = FALSE)
test_set <- heights[test_index, ]
train_set <- heights[-test_index, ]

#set.seed(1, sample.kind = "Rounding")
k <- seq(1,101,3)
F1_scores <- sapply(k, function(k){
  fit <-knn3(sex ~ height, data = train_set, k =k)
  y_hat <- factor(predict(fit, test_set, type = "class"))
  F1 <-F_meas(data = y_hat, reference = test_set$sex)
  c(F1)
})
max(F1_scores)
k[which(F1_scores == max(F1_scores))]

```
```{r}
library(dslabs)
library(caret)
data("tissue_gene_expression")
dat <- tissue_gene_expression 

set.seed(1, sample.kind = "Rounding")
test_index <- createDataPartition(dat$y,times =1, p = 0.5, list = FALSE)
test_set <- dat$x[test_index, ]
train_set <- dat$x[-test_index, ]
y_test <- dat$y[test_index]
y_train <- dat$y[-test_index]

#set.seed(1, sample.kind = "Rounding")
ks <- seq(1,11,2)
acc <- map_df(ks, function(ks){
  fit <-knn3(train_set, y_train, k = ks)
  y_hat <- factor(predict(fit, test_set, type = "class"))
  acc <- confusionMatrix(data = y_hat, reference = y_test)$overall["Accuracy"]
  c(acc)
})


dim(test_set)
dim(as.matrix(y_test))
dim(as.matrix(y_hat))
class(test_set)
ks <- 3
```

