

```{r}
library(dslabs)
library(tidyverse)
data("movielens")
head(movielens)

movielens %>% summarize(n_users = n_distinct(userId),
                        n_movies = n_distinct(movieId))

keep <- movielens %>%
  dplyr::count(movieId) %>%
  top_n(5) %>%
  pull(movieId)

tab <- movielens %>%
  filter(userId %in% c(13:20)) %>%
  filter(movieId %in% keep) %>%
  select(userId, title, rating) %>%
  spread(title, rating)
tab %>% knitr::kable()

users <- sample(unique(movielens$userId),100)
rafalib::mypar()
movielens %>% filter(userId %in% users) %>%
  select(userId, movieId, rating) %>%
  mutate(rating =1) %>%
  spread(movieId, rating) %>% select(sample(ncol(.),100)) %>%
  as.matrix() %>% t(.) %>%
  image(1:100,1:100, . ,xlab = "Movies", ylab = "Users")
abline(h=0:100+0.5, v=0:100+0.5, col = "grey")

movielens %>% dplyr::count(movieId) %>%
  ggplot(aes(n)) +
  geom_histogram(bins = 30, color = "black") +
  scale_x_log10() +
  ggtitle("Movies")

movielens %>% dplyr::count(userId) %>%
  ggplot(aes(n)) +
  geom_histogram(bins = 30, color = "black") +
  scale_x_log10() +
  ggtitle("Users")

library(caret)
set.seed(755, sample.kind = "Rounding")
test_index <- createDataPartition(y = movielens$rating, times = 1,
                                  p = 0.2, list = FALSE)
train_set <- movielens[-test_index,]
test_set <- movielens[test_index,]

test_set <- test_set %>% 
     semi_join(train_set, by = "movieId") %>%
     semi_join(train_set, by = "userId")

RMSE <- function(true_ratings, predicted_ratings){
     sqrt(mean((true_ratings - predicted_ratings)^2))
}

```
```{r}
mu <- mean(train_set$rating)
naive_rmse <- RMSE(test_set$rating, mu)

predictions <- rep(2.5,nrow(test_set))
RMSE(test_set$rating, predictions)

rmse_results <- tibble(method = "Just the average", RMSE = naive_rmse)

movie_avgs <- train_set %>% group_by(movieId) %>%
  summarize(b_i= mean(rating - mu))

movie_avgs %>% qplot(b_i, geom = "histogram", bins = 10, data = ., color = I("black"))
predicted_ratings <- mu + test_set %>% left_join(movie_avgs, by = "movieId") %>%
  .$b_i
model_1_rmse <- RMSE(predicted_ratings, test_set$rating)
rmse_results <- bind_rows(rmse_results,
                          data_frame(method="Movie Effect Model",
                                     RMSE = model_1_rmse ))

rmse_results  %>% knitr::kable()

```
```{r}
train_set %>% group_by(userId) %>%
  summarize(b_u = mean(rating)) %>%
  filter(n() >=100) %>%
  ggplot(aes(b_u)) + geom_histogram(bins = 30, color = "black")

user_avgs <- train_set %>% 
  left_join(movie_avgs, by = "movieId") %>%
  group_by(userId) %>% summarize(b_u = mean(rating - mu - b_i)) 

predicted_ratings <- test_set %>%
  left_join(movie_avgs, by = "movieId") %>%
  left_join(user_avgs, by = "userId") %>%
  mutate(pred = mu + b_i +b_u) %>%
  .$pred
model_2_rmse <- RMSE(predicted_ratings, test_set$rating)
rmse_results <- bind_rows(rmse_results,
                          data_frame(method="Movie + User Effect Model",
                                     RMSE = model_2_rmse ))
rmse_results  %>% knitr::kable()
```
```{r}
library(tidyverse)
library(lubridate)
library(dslabs)
library(ggplot2)
data("movielens")

movielens %>% dplyr::count(year, movieId) %>%
  ggplot(aes(factor(year),n)) + geom_boxplot() +
   scale_y_sqrt() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

dat <- movielens %>% dplyr::count(year, movieId) %>%
  group_by(year) %>% summarize(med = median(n)) 
dat$year[which.max(dat$med)]

movielens %>% group_by(movieId) %>%
	summarize(n = n(), year = as.character(first(year))) %>%
	qplot(year, n, data = ., geom = "boxplot") +
	coord_trans(y = "sqrt") +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
```
```{r}
library(data.table)
c <- c("Shawshank Redemption, The", "Forrest Gump")
movielens %>% filter(title %like% "Shawshank Redemption" & year >1993)
movielens %>% filter(title %in% c & year >1993) %>%
  group_by(title) %>% summarize(avg =mean(rating)) 

movielens %>% 
	filter(year >= 1993) %>%
	group_by(movieId) %>%
	summarize(n = n(), years = 2018 - first(year),
				title = title[1],
				rating = mean(rating)) %>%
	mutate(rate = n/years) %>%
	top_n(25, rate) %>%
	arrange(desc(rate))
```
```{r}
movielens %>% 
	filter(year >= 1993) %>%
	group_by(movieId) %>%
	summarize(n = n(), years = 2018 - first(year),
				title = title[1],
				rating = mean(rating)) %>%
	mutate(rate = n/years) %>%
  mutate(g = cut(rate,quantile(rate,seq(0,1,0.1)),include.Lowest =TRUE)) %>%
  group_by(g) %>%
 summarize(y= mean(rating)) %>%
  qplot(g,y,data = .)


 movielens %>% 
	filter(year >= 1993) %>%
	group_by(movieId) %>%
	summarize(n = n(), years = 2018 - first(year),
				title = title[1],
				rating = mean(rating)) %>%
	mutate(rate = n/years) %>%
	ggplot(aes(rate, rating)) +
	geom_point() +
	geom_smooth()
```
```{r}
 movielens <- mutate(movielens, date = as_datetime(timestamp))

movielens %>% mutate(wk = round_date(date, unit = "week")) %>%
  group_by(wk) %>%
  summarize(rating = mean(rating)) %>%
  ungroup() %>%
  ggplot(aes(wk,rating)) + geom_point() + geom_smooth()


movielens %>% mutate(date = round_date(date, unit = "week")) %>%
	group_by(date) %>%
	summarize(rating = mean(rating)) %>%
	ggplot(aes(date, rating)) +
	geom_point() +
	geom_smooth()
```
```{r}
movielens %>% group_by(genres) %>%
  summarize(n = n(), 
				avg_rating = mean(rating),
				sd_rating = sd(rating)) %>%
  filter(n > 1000) %>%
  arrange(avg_rating) %>%
  ggplot(aes(genres,avg_rating)) + 
  geom_point() +
  geom_errorbar(aes(x=genres, ymin = avg_rating-sd_rating,ymax = avg_rating+sd_rating)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

movielens %>% group_by(genres) %>%
	summarize(n = n(), avg = mean(rating), se = sd(rating)/sqrt(n())) %>%
	filter(n >= 1000) %>% 
	mutate(genres = reorder(genres, avg)) %>%
	ggplot(aes(x = genres, y = avg, ymin = avg - 2*se, ymax = avg + 2*se)) + 
	geom_point() +
	geom_errorbar() + 
	theme(axis.text.x = element_text(angle = 90, hjust = 1))
```




